spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "admin"
    password: "p"
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-root.xml"
    drop-first: false
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
springdoc:
  swagger-ui:
    url: "/swagger.html"


application:
  alpha-vantage:
    base-url: "https://alphavantage.co/query"
    api-key: "RZGJN19YQ6I081VI."
logging:
  level:
    de:
      stecknitz:
        backend: debug