[versions]
springBootVersion = "3.0.5"
springDependencyManagementVersion = "1.1.0"
lombokVersion = "1.18.26"

[libraries]
springBootStarter = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBootVersion" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-web-test", version.ref = "springBootVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "springBootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }