[versions]
springBootVersion = "3.0.5"
springDependencyManagementVersion = "1.1.0"
lombokVersion = "1.18.26"
springDataJpaVersion = "3.0.4"
postgresqlVersion = "42.6.0"
mapstructVersion = "1.5.3.Final"
testcontainerVesion = "1.18.0"


[libraries]
springBootStarter = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBootVersion" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" , version.ref = "springBootVersion" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBootVersion" }
testcontainer = { module = "org.testcontainers:testcontainers", version.ref = "testcontainerVesion" }
testcontainerPostgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainerVesion" }
testcontainerJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainerVesion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
springDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springDataJpaVersion" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresqlVersion" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstructVersion" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstructVersion" }
liquibaseCore = { module = "org.liquibase:liquibase-core" }

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "springBootVersion" }
springDependencyManagementPlugin = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }