@startuml
skinparam linetype ortho

entity "Stock" as stock {
  *isin : text
  --
  name : text
  wkn : text
  actual_price: text
}

entity "Depot" as depot {
  *id : number <<generiert>>
  --
  *user_email : text <<FS>>
}

entity "Investment" as investment {
  *investment_id : nummer <<generiert>>
  --
  *depot_id : number <<FS>>
  *stock_isin : text <<FS>>
  amount : number
  buyprice : number
  transaction_type: text
}

entity "User" as user {
    *email : text
    --
    *role : text <<FS>>
    first_name : text
    last_name : text
    password : text
    salt : text
}

entity "Role" as role {
    *name : text
    --
    description: text
}

entity "Deposit Account" as deposit_account {
    *id : number <<generiert>>
    --
    *depot_id : number <<FS>>
}

entity "Deposit Account Transaction" as deposit_account_transaction {
    *id : number <<generiert>>
    --
    *deposit_account_id : number <<FS>>
    *amount : number
    *type : text
}

stock ||-left-o{ investment
depot ||-right-|{ investment
user ||--|{ depot
role ||-left-o{ user
deposit_account ||-right-|| depot
deposit_account_transaction }o-up-|| deposit_account

@enduml