@startuml

[App] as app

[Main] as main

[Overview] as overview
[PortfolioOverview] as portfoliooverview
[PortfolioOverviewTitel] as portfoliooverviewtitel
[GefundeneInvestments] as gefundeneinvestments

[Sidebar] as sidebar
[SidebarTitel] as sidebartitel
[SidebarNavigation] as sidebarnavigation

app ... sidebar
app ... main

main ... overview

overview ... portfoliooverview

portfoliooverview ... portfoliooverviewtitel
portfoliooverview ... gefundeneinvestments

sidebar ... sidebartitel
sidebar ... sidebarnavigation


hide empty members
@enduml
